name: 'CI'
on:
  push:
    branches:
      - 'feature/*'
      - 'hotfix/*'
jobs:
  ci:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    steps:
      - name: 'Use Node.js 14.5'
        uses: 'actions/setup-node@v1'
        with:
          node-version: '14.5'
      - name: 'Check out repository'
        uses: 'actions/checkout@v2'
        with:
          fetch-depth: 0
      - name: 'Install dependencies'
        run: 'yarn install --frozen-lockfile'
      - name: 'Test'
        run: 'yarn test'
